In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.full(10, 38)

array([38, 38, 38, 38, 38, 38, 38, 38, 38, 38])

In [16]:
a=np.array([1,2,3,4,5,7,12])
a

array([ 1,  2,  3,  4,  5,  7, 12])

In [ ]:
# starting from 0
a[3] = 100

In [18]:
a

array([  1,   2,   3, 100,   5,   7,  12])

In [ ]:
# creating an array with a range of numbers
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# creating an array with a range of numbers starting from 3 to 10
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# creating an array with a range of numbers starting from 0 to 100 with 11 numbers
# the third argument is how many numbers we want in the range
# np.linspace(start, stop, num) 
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
# the third argument is step size
# np.arange doesn't include 'stop' value, so it will stop before reaching 101, if we want to include 100, we set stop to 101 (or any value greater than 100)
np.arange(0,101, 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

# Multi-dimentional arrays

In [33]:
np.zeros((3, 4))  # 3 rows, 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
n = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
    ])

n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
n[0,1] = 100 # changing value at first row, second column

n

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [40]:
n[2] # accessing the third row

array([7, 8, 9])

In [41]:
n[2] = [111, 222, 333]

n

array([[  1, 100,   3],
       [  4,   5,   6],
       [111, 222, 333]])

In [42]:
n[:, 2] # accessing the third column

array([  3,   6, 333])

In [43]:
n[1, :] # accessing the second row

array([4, 5, 6])

# Randomly generated arrays

In [44]:
np.random.rand(5,2)

array([[0.93110239, 0.88130847],
       [0.93189122, 0.94235983],
       [0.27329147, 0.6177061 ],
       [0.92961352, 0.2037777 ],
       [0.36168589, 0.20606881]])

In [ ]:
np.random.seed(2) # setting seed for reproducibility, so that we get the same random numbers every time we run the code
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
np.random.seed(2)
np.random.randn(5,2) # generating random numbers from a normal distribution (mean=0, std=1)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [49]:
np.random.seed(2)
100* np.random.randn(5,2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [51]:
np.random.seed(2)
np.random.randint(low=0, high=100, size = (5,2)) # generating random integers between 0 and 100, size is 5 rows and 2 columns

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [52]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [53]:
a+2


array([2, 3, 4, 5, 6])

In [60]:
b = 10*(a+2)
b

array([20, 30, 40, 50, 60])

In [61]:
11*(a+b)

array([220, 341, 462, 583, 704])

# Comparison operations

In [62]:
a

array([0, 1, 2, 3, 4])

In [63]:
a >= 2

array([False, False,  True,  True,  True])

In [64]:
b

array([20, 30, 40, 50, 60])

In [65]:
a>b

array([False, False, False, False, False])

In [67]:
a[a>b-22] # this will return an array with elements of 'a' that are greater than 'b-22'

array([0])

In [68]:
a[a>b] # accessing elements of a that are greater than b

array([], dtype=int64)

# Summarizing operations

In [69]:
a

array([0, 1, 2, 3, 4])

In [70]:
a.mean()

np.float64(2.0)

In [71]:
a.std()

np.float64(1.4142135623730951)

In [ ]:
n.min() # minimum value in the array

np.int64(1)